// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

// User is an object representing the database table.
type User struct {
	Phone    int64  `json:"phone"`
	Password string `json:"password"`
	Name     string `json:"name"`
	IsAdmin  int    `json:"is_admin"`
}
